shopping = []
shopping.append("Bottle")
print(shopping)
shopping.append("Tiffin")
shopping.append("Lunch Box")
print(shopping)
item = input("Enter shopping item: ")
shopping.append(item)
print(shopping)
item = input("Enter shopping item: ")
shopping.append(item)
print(shopping)
shopping = []
item1 = input("Enter shopping item: ")
shopping.append(item1)
item2 = input("Enter shopping item: ")
shopping.append(item2)
item3 = input("Enter shopping item: ")
shopping.append(item3)
print("Shopping List:", shopping)
shopping = []
item1 = input("Enter shopping item: ")
shopping.append(item1)
item2 = input("Enter shopping item: ")
shopping.append(item2)
item3 = input("Enter shopping item: ")
shopping.append(item3)
item4 = input("Enter shopping item: ")
shopping.append(item4)
print("Shopping List:", shopping)
print(len(shopping))
shopping.remove(item2)
print("Shopping List after removing", item2, ":", shopping)
print("Final Shopping List:", shopping)
shopping = []
item1 = input("Enter shopping item: ")
shopping.append(item1)
item2 = input("Enter shopping item: ")
shopping.append(item2)
item3 = input("Enter shopping item: ")
shopping.append(item3)
item4 = input("Enter shopping item: ")
shopping.append(item4)
print("Shopping List:", shopping)
search_item = input("Enter item to search: ")
if search_item in shopping:
    print(search_item, "is in the shopping list.")
else:
    print(search_item, "is not in the shopping list.") 
shopping = []
item1 = input("Enter item: ")
shopping.append(item1)
item2 = input("Enter item: ")
shopping.append(item2)
item3 = input("Enter item: ")
shopping.append(item3)
print(shopping)
search_item = input("Search item: ")
if search_item in shopping:
    print("Found!")
    print("Index:", shopping.index(search_item))
else:
    print("Item not found.")